version: '3'
services:
  whisper_gpu:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: 'whisper-gpu'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./main:/root/main/
      - ./audio:/root/audio/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
